[package]
name = "fuse-query"
version = "0.1.0"
description = "A real-time Cloud Distributed Query Engine"
authors = ["BohuTANG <overred.shuttler@gmail.com>"]
license = "Apache-2.0"
include = [
    "benches/*.rs",
    "src/**/*.rs",
    "Cargo.toml",
]
edition = "2018"

[[bin]]
name = "fuse-query"
path = "src/bin/fuse-query.rs"

[dependencies]
arrow = { git = "https://github.com/apache/arrow", rev="46161d2" }
arrow-flight = { git = "https://github.com/apache/arrow", rev="46161d2" }
async-std = "1.9.0"
async-trait = "0.1"
dyn-clone = "1.0.4"
futures = "0.3"
indexmap = "1.6.1"
lazy_static = "1.4.0"
log = "0.4"
metrics = "0.14.2"
metrics-exporter-prometheus = "0.3.0"
msql-srv = "0.9"
num = "0.4"
num_cpus = "1.0"
paste = "^1.0"
prost = "0.7"
rand = "0.8.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
simplelog = "0.9"
snafu = "0.6.8"
sqlparser = "0.8"
structopt = "0.3"
thiserror = "1.0"
threadpool = "1.8.1"
tokio = { version = "1.0", features = ["macros", "rt","rt-multi-thread", "sync"] }
tokio-stream = "0.1"
tonic = "0.4"
warp = "0.3.0"
uuid = { version = "0.8", features = ["serde", "v4"] }

[dev-dependencies]
criterion = "0.3.4"
pretty_assertions = "1.0"

[build-dependencies]
tonic-build = { version = "0.4" }

[[bench]]
name = "bench_main"
harness = false

[profile.release]
lto = "thin"
